#
# Copyright 2013, Enrico Stahn <enrico.stahn@zanui.com.au>
# Copyright 2013, Zanui <engineering@zanui.com.au>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

default['nginx']['port'] = 80

default['thumbor']['processes'] = 1
default['thumbor']['base_port'] = 8888

default['thumbor']['key'] = 'MY_SECURE_KEY'

default['thumbor']['user'] = 'thumbor'
default['thumbor']['group'] = 'thumbor'

################################### Logging ####################################

## Log Format to be used by thumbor when writing log messages.
## Defaults to: %(asctime)s %(name)s:%(levelname)s %(message)s
default['thumbor']['options']['THUMBOR_LOG_FORMAT'] = '%(asctime)s %(name)s:%(levelname)s %(message)s'

## Date Format to be used by thumbor when writing log messages.
## Defaults to: %Y-%m-%d %H:%M:%S
default['thumbor']['options']['THUMBOR_LOG_DATE_FORMAT'] = '%Y-%m-%d %H:%M:%S'

################################################################################

################################### Imaging ####################################

## Max width in pixels for images read or generated by thumbor
## Defaults to: 0
default['thumbor']['options']['MAX_WIDTH'] = 0

## Max height in pixels for images read or generated by thumbor
## Defaults to: 0
default['thumbor']['options']['MAX_HEIGHT'] = 0

## Min width in pixels for images read or generated by thumbor
## Defaults to: 1
default['thumbor']['options']['MIN_WIDTH'] = 0

## Min width in pixels for images read or generated by thumbor
## Defaults to: 1
default['thumbor']['options']['MIN_HEIGHT'] = 0

## Allowed domains for the http loader to download. These are regular
## expressions.
## Defaults to: []
default['thumbor']['options']['ALLOWED_SOURCES'] = []

## Quality index used for generated JPEG images
## Defaults to: 80
default['thumbor']['options']['QUALITY'] = 80

## Quality index used for generated WebP images. If not set (None) the same level
## of JPEG quality will be used.
## Defaults to: None
default['thumbor']['options']['WEBP_QUALITY'] = 'None'

## Specifies whether WebP format should be used automatically if the request
## accepts it (via Accept header)
## Defaults to: False
default['thumbor']['options']['AUTO_WEBP'] = 'True'

## Max AGE sent as a header for the image served by thumbor in seconds
## Defaults to: 86400
default['thumbor']['options']['MAX_AGE'] = 86_400

## Indicates the Max AGE header in seconds for temporary images (images with
## failed smart detection)
## Defaults to: 0
default['thumbor']['options']['FACE_DETECTOR_CASCADE_FILE'] = 0

## Indicates whether thumbor should rotate images that have an Orientation EXIF
## header
## Defaults to: False
default['thumbor']['options']['RESPECT_ORIENTATION'] = 'False'

## Ignore errors during smart detections and return image as a temp image (not
## saved in result storage and with MAX_AGE_TEMP_IMAGE age)
## Defaults to: False
default['thumbor']['options']['IGNORE_SMART_ERRORS'] = 'False'

## Preserves exif information in generated images. Increases image size in
## kbytes, use with caution.
## Defaults to: False
default['thumbor']['options']['PRESERVE_EXIF_INFO'] = 'False'

## Indicates whether thumbor should enable the EXPERIMENTAL support for animated
## gifs.
## Defaults to: True
default['thumbor']['options']['ALLOW_ANIMATED_GIFS'] = 'True'

################################################################################

################################ Extensibility #################################

## The loader thumbor should use to load the original image. This must be the
## full name of a python module (python must be able to import it)
## Defaults to: thumbor.loaders.http_loader
default['thumbor']['options']['LOADER'] = 'thumbor.loaders.http_loader'

## The file storage thumbor should use to store original images. This must be the
## full name of a python module (python must be able to import it)
## Defaults to: thumbor.storages.file_storage
default['thumbor']['options']['STORAGE'] = 'thumbor.storages.file_storage'

## The result storage thumbor should use to store generated images. This must be
## the full name of a python module (python must be able to import it)
## Defaults to: None
default['thumbor']['options']['RESULT_STORAGE'] = 'None'

## The imaging engine thumbor should use to perform image operations. This must
## be the full name of a python module (python must be able to import it)
## Defaults to: thumbor.engines.pil
default['thumbor']['options']['ENGINE'] = 'thumbor.engines.pil'

################################################################################

################################### Security ###################################

## The security key thumbor uses to sign image URLs
## Defaults to: MY_SECURE_KEY
default['thumbor']['options']['SECURITY_KEY'] = node['thumbor']['key']

## Indicates if the /unsafe URL should be available
## Defaults to: True
default['thumbor']['options']['ALLOW_UNSAFE_URL'] = 'True'

## Indicates if encrypted (old style) URLs should be allowed
## Defaults to: True
default['thumbor']['options']['ALLOW_OLD_URLS'] = 'True'

################################################################################

################################# File Loader ##################################

## The root path where the File Loader will try to find images
## Defaults to: /tmp
default['thumbor']['options']['FILE_LOADER_ROOT_PATH'] = '/tmp'

################################################################################

################################# HTTP Loader ##################################

## The maximum number of seconds libcurl can take to connect to an image being
## loaded
## Defaults to: 5
default['thumbor']['options']['HTTP_LOADER_CONNECT_TIMEOUT'] = 5

## The maximum number of seconds libcurl can take to download an image
## Defaults to: 20
default['thumbor']['options']['HTTP_LOADER_REQUEST_TIMEOUT'] = 20

## Indicates whether libcurl should follow redirects when downloading an image
## Defaults to: True
default['thumbor']['options']['HTTP_LOADER_FOLLOW_REDIRECTS'] = 'True'

## Indicates the number of redirects libcurl should follow when downloading an
## image
## Defaults to: 5
default['thumbor']['options']['HTTP_LOADER_MAX_REDIRECTS'] = 5

## Indicates whether thumbor should forward the user agent of the requesting user
## Defaults to: False
default['thumbor']['options']['HTTP_LOADER_FORWARD_USER_AGENT'] = 'False'

## Default user agent for thumbor http loader requests
## Defaults to: Thumbor/3.15.0
default['thumbor']['options']['HTTP_LOADER_DEFAULT_USER_AGENT'] = 'Thumbor/3.15.0'

## The proxy host needed to load images through
## Defaults to: None
default['thumbor']['options']['HTTP_LOADER_PROXY_HOST'] = 'None'

## The proxy port for the proxy host
## Defaults to: None
default['thumbor']['options']['HTTP_LOADER_PROXY_PORT'] = 'None'

## The proxy username for the proxy host
## Defaults to: None
default['thumbor']['options']['HTTP_LOADER_PROXY_USERNAME'] = 'None'

## The proxy password for the proxy host
## Defaults to: None
default['thumbor']['options']['HTTP_LOADER_PROXY_PASSWORD'] = 'None'

################################################################################

################################# File Storage #################################

## Expiration in seconds for the images in the File Storage. Defaults to one
## month
## Defaults to: 2592000
default['thumbor']['options']['STORAGE_EXPIRATION_SECONDS'] = 2_592_000

## Indicates whether thumbor should store the signing key for each image in the
## file storage. This allows the key to be changed and old images to still be
## properly found
## Defaults to: False
default['thumbor']['options']['STORES_CRYPTO_KEY_FOR_EACH_IMAGE'] = 'False'

## The root path where the File Storage will try to find images
## Defaults to: /tmp/thumbor/storage
default['thumbor']['options']['FILE_STORAGE_ROOT_PATH'] = '/tmp/thumbor/storage'

################################################################################

#################################### Upload ####################################

## Max size in Kb for images uploaded to thumbor
## Aliases: MAX_SIZE
## Defaults to: 0
default['thumbor']['options']['UPLOAD_MAX_SIZE'] = 0

## Indicates whether thumbor should enable File uploads
## Aliases: ENABLE_ORIGINAL_PHOTO_UPLOAD
## Defaults to: False
default['thumbor']['options']['UPLOAD_ENABLED'] = 'False'

## The type of storage to store uploaded images with
## Aliases: ORIGINAL_PHOTO_STORAGE
## Defaults to: thumbor.storages.file_storage
default['thumbor']['options']['UPLOAD_PHOTO_STORAGE'] = 'thumbor.storages.file_storage'

## Indicates whether image deletion should be allowed
## Aliases: ALLOW_ORIGINAL_PHOTO_DELETION
## Defaults to: False
default['thumbor']['options']['UPLOAD_DELETE_ALLOWED'] = 'False'

## Indicates whether image overwrite should be allowed
## Aliases: ALLOW_ORIGINAL_PHOTO_PUTTING
## Defaults to: False
default['thumbor']['options']['UPLOAD_PUT_ALLOWED'] = 'False'

## Default filename for image uploaded
## Defaults to: image
default['thumbor']['options']['UPLOAD_DEFAULT_FILENAME'] = 'image'

################################################################################

############################### MongoDB Storage ################################

## MongoDB storage server host
## Defaults to: localhost
default['thumbor']['options']['MONGO_STORAGE_SERVER_HOST'] = 'localhost'

## MongoDB storage server port
## Defaults to: 27017
default['thumbor']['options']['MONGO_STORAGE_SERVER_PORT'] = 27_017

## MongoDB storage server database name
## Defaults to: thumbor
default['thumbor']['options']['MONGO_STORAGE_SERVER_DB'] = 'thumbor'

## MongoDB storage image collection
## Defaults to: images
default['thumbor']['options']['MONGO_STORAGE_SERVER_COLLECTION'] = 'images'

################################################################################

################################ Redis Storage #################################

## Redis storage server host
## Defaults to: localhost
default['thumbor']['options']['REDIS_STORAGE_SERVER_HOST'] = 'localhost'

## Redis storage server port
## Defaults to: 6379
default['thumbor']['options']['REDIS_STORAGE_SERVER_PORT'] = 6379

## Redis storage database index
## Defaults to: 0
default['thumbor']['options']['REDIS_STORAGE_SERVER_DB'] = 0

## Redis storage server password
## Defaults to: None
default['thumbor']['options']['REDIS_STORAGE_SERVER_PASSWORD'] = 'None'

################################################################################

############################### Memcache Storage ###############################

## List of Memcache storage server hosts
## Defaults to: ['localhost:11211']
default['thumbor']['options']['MEMCACHE_STORAGE_SERVERS'] = [
    'localhost:11211',
]

################################################################################

################################ Mixed Storage #################################

## Mixed Storage file storage. This must be the full name of a python module
## (python must be able to import it)
## Defaults to: thumbor.storages.no_storage
default['thumbor']['options']['MIXED_STORAGE_FILE_STORAGE'] = 'thumbor.storages.no_storage'

## Mixed Storage signing key storage. This must be the full name of a python
## module (python must be able to import it)
## Defaults to: thumbor.storages.no_storage
default['thumbor']['options']['MIXED_STORAGE_CRYPTO_STORAGE'] = 'thumbor.storages.no_storage'

## Mixed Storage detector information storage. This must be the full name of a
## python module (python must be able to import it)
## Defaults to: thumbor.storages.no_storage
default['thumbor']['options']['MIXED_STORAGE_DETECTOR_STORAGE'] = 'thumbor.storages.no_storage'

################################################################################

##################################### Meta #####################################

## The callback function name that should be used by the META route for JSONP
## access
## Defaults to: None
default['thumbor']['options']['META_CALLBACK_NAME'] = 'None'

################################################################################

################################## Detection ###################################

## List of detectors that thumbor should use to find faces and/or features. All
## of them must be full names of python modules (python must be able to import
## it)
## Defaults to: []
default['thumbor']['options']['DETECTORS'] = []

## The cascade file that opencv will use to detect faces
## Defaults to: haarcascade_frontalface_alt.xml
default['thumbor']['options']['FACE_DETECTOR_CASCADE_FILE'] = 'haarcascade_frontalface_alt.xml'

################################################################################

################################### Filters ####################################

## List of filters that thumbor will allow to be used in generated images. All of
## them must be full names of python modules (python must be able to import
## it)
## Defaults to: ['thumbor.filters.brightness', 'thumbor.filters.contrast', 'thumbor.filters.rgb', 'thumbor.filters.round_corner', 'thumbor.filters.quality', 'thumbor.filters.noise', 'thumbor.filters.watermark', 'thumbor.filters.equalize', 'thumbor.filters.fill', 'thumbor.filters.sharpen', 'thumbor.filters.strip_icc', 'thumbor.filters.frame', 'thumbor.filters.grayscale', 'thumbor.filters.format', 'thumbor.filters.max_bytes']
default['thumbor']['options']['FILTERS'] = [
#        'thumbor.filters.brightness',
#        'thumbor.filters.contrast',
#        'thumbor.filters.rgb',
#        'thumbor.filters.round_corner',
#        'thumbor.filters.quality',
#        'thumbor.filters.noise',
#        'thumbor.filters.watermark',
#        'thumbor.filters.equalize',
#        'thumbor.filters.fill',
#        'thumbor.filters.sharpen',
#        'thumbor.filters.strip_icc',
#        'thumbor.filters.frame',
#        'thumbor.filters.grayscale',
#        'thumbor.filters.format',
#        'thumbor.filters.max_bytes',
]

################################################################################

################################ Result Storage ################################

## Expiration in seconds of generated images in the result storage
## Defaults to: 0
default['thumbor']['options']['RESULT_STORAGE_EXPIRATION_SECONDS'] = 0

## Path where the Result storage will store generated images
## Defaults to: /tmp/thumbor/result_storage
default['thumbor']['options']['RESULT_STORAGE_FILE_STORAGE_ROOT_PATH'] = '/tmp/thumbor/result_storage'

## Indicates whether unsafe requests should also be stored in the Result Storage
## Defaults to: False
default['thumbor']['options']['RESULT_STORAGE_STORES_UNSAFE'] = 'False'

################################################################################

############################ Queued Redis Detector #############################

## Server host for the queued redis detector
## Defaults to: localhost
default['thumbor']['options']['REDIS_QUEUE_SERVER_HOST'] = 'localhost'

## Server port for the queued redis detector
## Defaults to: 6379
default['thumbor']['options']['REDIS_QUEUE_SERVER_PORT'] = 6379

## Server database index for the queued redis detector
## Defaults to: 0
default['thumbor']['options']['REDIS_QUEUE_SERVER_DB'] = 0

## Server password for the queued redis detector
## Defaults to: None
default['thumbor']['options']['REDIS_QUEUE_SERVER_PASSWORD'] = 'None'

################################################################################

############################# Queued SQS Detector ##############################

## AWS key id
## Defaults to: None
default['thumbor']['options']['SQS_QUEUE_KEY_ID'] = 'None'

## AWS key secret
## Defaults to: None
default['thumbor']['options']['SQS_QUEUE_KEY_SECRET'] = 'None'

## AWS SQS region
## Defaults to: us-east-1
default['thumbor']['options']['SQS_QUEUE_REGION'] = 'us-east-1'

################################################################################

#################################### Errors ####################################

## This configuration indicates whether thumbor should use a custom error
## handler.
## Defaults to: False
default['thumbor']['options']['USE_CUSTOM_ERROR_HANDLING'] = 'False'

## Error reporting module. Needs to contain a class called ErrorHandler with a
## handle_error(context, handler, exception) method.
## Defaults to: thumbor.error_handlers.sentry
default['thumbor']['options']['ERROR_HANDLER_MODULE'] = 'thumbor.error_handlers.sentry'

## File of error log as json
## Defaults to: None
default['thumbor']['options']['ERROR_FILE_LOGGER'] = 'None'

################################################################################

############################### Errors - Sentry ################################

## Sentry thumbor project dsn. i.e.: http://5a63d58ae7b94f1dab3dee740b301d6a:73ee
## a45d3e8649239a973087e8f21f98@localhost:9000/2
## Defaults to:
default['thumbor']['options']['SENTRY_DSN_URL'] = ''

################################################################################
